### ISSUE TITLE
Avatar not being correctly refreshed after selecting a teacher

### ISSUE THREAD

**Issue by nelsonalmendra** [driverpt/Thoth-Android#10]
Select one teacher, press back then select another teacher and the avatar is from the first one instead of the current.

**Comment by driverpt** [comment]
I think i've already fixed this in commit dc4316194b429532b56215609e25afc65341c8ed, need to test it though

**Comment by driverpt** [comment]
Fixed in commit 67481e421792bdf27530732c5c44506dfa231cf6
Closing.
